### ISSUE TITLE
Input historical case data

### ISSUE THREAD

**Issue by chekdotdev** [chekcreative/ohio-ready#1]
Using [this google sheet](https://docs.google.com/spreadsheets/d/1Xpib33TktK-asV4yqF05p6pmIuYKHvHoc386eT-OooQ/edit#gid=704172440), import historical case data into the [api](https://ohioready-api.zwink.net/admin/api/case/) using the **import** functionality.

The csv file must be formatted as `id, as_of, county, total, deaths, recovered`.

**Comment by BradGriffith** [comment]
Where did the data in the Google Sheet come from? I see the latest data is from 3/25.

I don't have API access. Can you add me, @jchekanoff ?

**Comment by chekdotdev** [comment]
@BradGriffith I imported through 3/29. There's a good lag between when the press conference is happening and when their hosted CSV is updated. I updated my sheet with a link to that csv. I just do a `CTRL+F` to see if the date I'm looking for is there before downloading.

I'll shoot API credentials to you!
