### ISSUE TITLE
Connect left sidebar to redux

### ISSUE THREAD

**Issue by tjvick** [chekcreative/ohio-ready#11]
The left sidebar component should be connected to redux, such that changes to the date value in the redux store are reflected in the sidebar.

The News list and the right-side date display are already connected.

**Comment by rpie3** [comment]
Ignore the above, I referenced incorrect issue number

**Comment by rpie3** [comment]
PR #12 connects the statistics section.

**Comment by rpie3** [comment]
@jchekanoff - any insight to provide here as to what the county dropdown should update across the app?

![Screen Shot 2020-03-30 at 4 17 19 PM](https://user-images.githubusercontent.com/25672665/77957747-f4c3df80-72a1-11ea-9025-4374e60677fd.png)

**Comment by chekdotdev** [comment]
The aggregate data at the top of the page can key into the data available in this API call as well:

```https://ohioready-api.zwink.net/v1/case_summary.agg/?aggregate[Sum]=total&aggregate[Sum]=deaths&aggregate[Sum]=recovered&group_by[as_of]```

The "county" drop down is a bit confusing to me, too. I'll check into what Brandon has to say.
