### ISSUE TITLE
Full screen chart functionality

### ISSUE THREAD

**Issue by chekdotdev** [chekcreative/ohio-ready#45]
The chart should have a full screen button that converts the "weekly" layout to a "daily" layout. 

We'll need to create min-width on the bars, such that if we have 100 days in full screen, the user can scroll/drag the chart horizontally to go back and forth.

**Comment by tjvick** [comment]
Do we imagine this full screen chart will be on a separate page/route, open as a modal, or somehow expand from the sidebar chart?

**Comment by chekdotdev** [comment]
I could see a modal or a sidebar slide in-out (effectively same experience as a modal). We have some leeway here, since there's no design in inVision. I could hit Brandon up for a more detailed chart.

**Comment by tjvick** [comment]
Created a modal full-screen chart, but have not implemented min-width on the bars.  Creating a separate issue for that part.
