### ISSUE TITLE
UI seems to be calling backend /event/ endpoint multiple times

### ISSUE THREAD

**Issue by rzwink** [chekcreative/ohio-ready#46]
Awesome job on the site.

According to Chrome Developer Tools Network tab the /events/ endpoint is hit three times when the page is drawn.  Would be ideal to only hit it once.

Steps to reproduce:

1. Start Chrome and enable the developer tools
2. Click the Network tab
3. (optional) enable filter "XHR" to only see API calls
4. To to https://www.ohioready.org
5. Observe 1 x call to /case/ and 3 x calls to /event/  
6. Observe that the /event/ calls all return the same data.

**Comment by chekdotdev** [comment]
@rzwink can you confirm this is no longer an issue?

**Comment by rzwink** [comment]
Confirmed, this is no longer an issue.

FYI, while confirming this is no longer an issue I noticed there are now 2 x calls to the /case/ end point.  The as_of date is different, so this may be intentional.  So just FYI, today for example two calls are made:

/case/?as_of=2020-04-**03**&page[size]=100
/case/?as_of=2020-04-**04**&page[size]=100

**Comment by rzwink** [comment]
Actually, nevermind, I now see that these calls are made because there are two articles displayed w/ those dates.  So I imagine this is by design.  I see the data changes when I scroll.  Awesome job w/ that feature by the way, very cool.

**Comment by tjvick** [comment]
The back-to-back call for cases on page load is likely because we do not have case data for today yet. If there is no case data we can display, we roll back a day until we find some.

**Comment by rzwink** [comment]
ah, cool.  thanks for clarification
