### ISSUE TITLE
Bug - Event appears twice

### ISSUE THREAD

**Issue by rzwink** [chekcreative/ohio-ready#52]
**Type**
- [ ] Feature Request
- [ ] Correction
- [x] Issue / Bug
- [ ] Question 

**Describe the report**
When scrolling through events I noticed the issue at the bottom that was the last before the API call that brought in new articles appears twice.

**To Reproduce** `(bugs only)`
1. Go to www.ohioready.org
2. Scroll down until current page exhausted and new events are displayed
3. Notice a duplicate entry

**Expected behavior** `(bugs and feature requests only)`
Events are listed once and not duplicated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest

**Additional context**
I posted a screenshot in #prjct-ohioready slack

**Comment by chekdotdev** [comment]
Marked as `blocked` until we hear from @rzwink if this can be resolved API side.

> it might be an API issue, I see its listed at bottom of page 1, and at the top of page two from the /event/ endpoint, so I think its my issue....
> – [Rob](https://app.slack.com/team/U010DR4F4MU) on slack

![image](https://user-images.githubusercontent.com/28504852/78453734-9c099380-7661-11ea-827a-b93cb0d64a4d.png)

**Comment by tjvick** [comment]
@rzwink I just took another look at this.  I believe this stems from our event ordering not being specific enough.  I see that it is ordered by `published_on`, but if several events have the same date, then their order is not guaranteed.  The order may change when you change `page[number]` or `page[size]`.  As a result, we end up seeing duplicate events, and are missing others.

From https://docs.djangoproject.com/en/3.0/ref/models/options/#ordering :
"If a query doesn’t have an ordering specified, results are returned from the database in an unspecified order. A particular ordering is guaranteed only when ordering by a set of fields that uniquely identify each object in the results"

Maybe we can add `created_on` or `title` as a secondary ordering field to the events?

**Comment by rzwink** [comment]
Great idea, I will add the id column after the published on date.

**Comment by tjvick** [comment]
I have not seen this issue since @rzwink updated the API sorting
