### ISSUE TITLE
Feature Request - Search

### ISSUE THREAD

**Issue by chekdotdev** [chekcreative/ohio-ready#56]
**Type**
- [x] Feature Request
- [ ] Correction
- [ ] Issue / Bug
- [ ] Question 

**Describe the report**
Implement filter functionality to allow visitors to search for specific tags. 

**Expected behavior**
See the [invision](https://invis.io/XKWIQF9Y2MG#/412383371_Menu) screen for desktop and mobile filters.

Per @slythr:

> it’ll ‘typeahead’ against the library of chips/tags. That’s probably the easiest to execute.
> the chips shown are most popular by category. just an idea
> Autocomplete materialui component: https://material-ui.com/components/autocomplete/

**Note:** This will require a new [API route](https://github.com/rzwink/ohioready-api/issues/13) to get most popular tags, CC @rzwink

**Screenshots**

<img width="956" alt="image" src="https://user-images.githubusercontent.com/28504852/78516672-67442c00-7788-11ea-98e9-d97743ce037e.png">

<img width="367" alt="image" src="https://user-images.githubusercontent.com/28504852/78516713-8fcc2600-7788-11ea-87e2-4f0ceafa3e32.png">

**Note:** for the mobile version, we can skip the select input and just show the top tags overall.

**Comment by chekdotdev** [comment]
Category 1 will be `tag`, or 
http://ohioready-api.zwink.net/v1/tag/

Category 2 will be `authorizer`, or 
http://ohioready-api.zwink.net/v1/authorizer/

Category 3 will be `location`, or
<img width="115" alt="image" src="https://user-images.githubusercontent.com/28504852/79014643-58b79500-7b39-11ea-970b-7635d86d170e.png">

We're still getting the `sort by popularity` route, but we can do first results for now.

**Comment by chekdotdev** [comment]
@ducharmemp -- Your most recent PR removed the chips other than "tags". Is there a way to make sure we still get "authorizer" and "region" tags in the event cards?

New:
<img width="874" alt="image" src="https://user-images.githubusercontent.com/28504852/79245773-89077800-7e46-11ea-9c0b-1c6ffb0c535b.png">


Old: 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/28504852/79245855-ad635480-7e46-11ea-95e6-fddaf8b12e8b.png">

**Comment by ducharmemp** [comment]
Got it, I'll implement a fix asap
