### ISSUE TITLE
Chart component

### ISSUE THREAD

**Issue by chekdotdev** [chekcreative/ohio-ready#7]
Create chart component, fed by the date in redux.

**Comment by rpie3** [comment]
per @jchekanoff there is a pause on this component - don't work on this until further indicated

**Comment by chekdotdev** [comment]
This chart component can use the aggregate data feed to create the chart. We're good to Develop it out whenever ready.

```https://ohioready-api.zwink.net/v1/case_summary.agg/?aggregate[Sum]=total&aggregate[Sum]=deaths&aggregate[Sum]=recovered&group_by[as_of]```

**Comment by chekdotdev** [comment]
This chart should take `SATURDAY` numbers from each week (starting with March 6 or 13, whichever looks better) and display that as the sidebar data.

**Comment by chekdotdev** [comment]
This blocks #45. Eventually, the full screen data will show each day, with a scroll behavior if the chart can't fit all bars. This sidebar chart component will not have such behavior.

**Comment by tjvick** [comment]
Note that our data starts on March 18th, so the first Saturday will be March 21.   April 4th will be our 3rd Saturday.
